# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LANG: "en_GB.UTF-8"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set locale to Great Britain
      run: |
        sudo locale-gen en_GB.UTF-8
        sudo update-locale LANG=en_GB.UTF-8
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
